##
# Shorthand for the default node image.
##
default_node_image: &default_node_image
    docker:
      - image: circleci/node:8.10.0
    
    working_directory: ~/repo

version: 2
jobs:
  ################################
  # Dependencies
  ################################

  dependencies:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Install dependencies.
      - run:
          name: Gathering Tiberium
          command: yarn install

      # Save to cache.
      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  ################################
  # Tests/linting
  ################################

  lint:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Linting.
      - run:
          name: Stop! It's linter time
          command: yarn lint

  unit_tests:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Install dependencies.
      - run:
          name: Starting the web 3.0
          command: yarn start:network

      # Tests.
      - run:
          name: Destroy your Companion Cube or the testing cannot continue
          command: yarn test
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - dependencies
          filters:
            tags:
              only: /.*/
      - unit_tests:
          requires:
            - dependencies
          filters:
            tags:
              only: /.*/
